### ISSUE TITLE
Fix `Sakilla` schema restore bug 

### ISSUE THREAD

**Issue by rocket-3** [databasegit/dbgit#15]
> @rultor deploy, tests=`*IntegrationTest*#*CustomTypes*`

@rocket-3 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24603-859229343) (spent 4min)

```
|   >             Restoring indexes for table public/payment.tbl ... OK
|   >         Restoring function public/_group_concat.fnc ... OK
|   >         Restoring function public/film_in_stock.fnc ... OK03:13 ERROR [App.java:41] : Error execute dbgit
|   > ru.fusionsoft.dbgit.core.ExceptionDBGitRestore: Restore objects error
|   >   at ru.fusionsoft.dbgit.adapters.DBAdapter.restoreDataBase(DBAdapter.java:160)
|   >   at ru.fusionsoft.dbgit.core.GitMetaDataManager.restoreDataBase(GitMetaDataManager.java:384)
|   >   at ru.fusionsoft.dbgit.command.CmdRestore.execute(CmdRestore.java:183)
|   >   at ru.fusionsoft.dbgit.App.executeDbGitCommand(App.java:57)
|   >   at ru.fusionsoft.dbgit.App.main(App.java:29)
|   > Caused by: ru.fusionsoft.dbgit.core.ExceptionDBGitRestore: Error restore public/film_in_stock.fnc
|   >   at ru.fusionsoft.dbgit.postgres.DBRestoreFunctionPostgres.restoreMetaObject(DBRestoreFunctionPostgres.java:73)
|   >   at ru.fusionsoft.dbgit.adapters.DBAdapter.restoreDataBase(DBAdapter.java:140)
|   >   ... 4 common frames omitted
|   > Caused by: org.postgresql.util.PSQLException: ERROR: function inventory_in_stock(integer) does not exist
|   >   Hint: No function matches the given name and argument types. You might need to add explicit type casts.
|   >   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
|   >   at ru.fusionsoft.dbgit.statement.StatementLogging.execute(StatementLogging.java:178)
|   >   at ru.fusionsoft.dbgit.postgres.DBRestoreFunctionPostgres.restoreMetaObject(DBRestoreFunctionPostgres.java:61)
|   >   ... 5 common frames omitted
|   java.lang.Exception: Process exited with error, code 1
Fri Jun 11 05:14:36 CEST 2021
```

**Comment by rocket-3** [comment]
@rultor, merge, tests=`*IntegrationTest*#*CustomTypes*`
